server:
  port: 6400

spring:
  application:
    name: group-purchase

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.96.193.174:3306/group_purchase?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ENC(UN+JxSOD6zt45ZdIMeqs8f9lTm0bHIQ6pIu9hvM9liXSELHEoq9Ex3g4Y/Gug312)
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 60000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

  data:
    redis:
      database: 0
      host: 119.96.193.174
      password: ENC(UKZxR/QnjQ9efGcsK5GpybMf8Uz+WI2x016a+o6RktGzGqxItMNyg/8GsDPN3Acu)
      port: 6379
      # 连接超时时间
      timeout: 30s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

mybatis-plus:
  mapper-locations:  classpath:/META-INF/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:  cn.com.xuct.group.purchase.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  token-prefix: Bearer

feign:
  # Okhttp参数配置
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    max-connections: 200 # 默认值
    max-connections-per-route: 50 # 默认值


wx:
  miniapp:
    configs:
      - appid: wxd1cee317f1b0df7c
        secret: ENC(sSGkzeqOqCbuAG8kBL2x4jYn71iKMVzD7tJO6LroLoRTXPhWuA/SWtFm0dNu1Fr9sBK/0ZU7gMtClzdn+uz1oat5lvSsrw6SM6CMRYBCX8Y=)


img:
  url:
    path: https://www.imgurl.org/api/v2/upload
    token: ENC(9Xikx4mJJcfLicu25nUrYIPX/bRKW1LO3Yvto26omiVFG4uGXAgiDpaC/gOQvry0DwtVjQuKhfAeQeZWJUtWdpn4+ksiS5nFi1+B0Wpq5oU=)
    uid:  0b4d45e4a19ba56f7139294d78f5b2d5
    tmpdir: /var/data/upload