server:
  port: 6400

spring:
  application:
    name: group-purchase

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.96.193.174:3306/group_purchase?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ENC(TS8pO2QiQDmLOI9m569voPYV7iWS6gNsLaCFQbGIUgCT8MRsc3pTMOEYTfhfj8B3)
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 60000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

  data:
    redis:
      database: 0
      host: 119.96.193.174
      password: ENC(JCZLsa4nak7hGEjCWDvrcSe1dDirXu04s5L9sv0blvgTGt3T9pzo3Qe12ubN1B/A)
      port: 6379
      # 连接超时时间
      timeout: 30s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

mybatis-plus:
  mapper-locations:  classpath:/META-INF/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:  cn.com.xuct.group.purchase.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  token-prefix: Bearer

wx:
  minimap:
    configs:
      - appid: wxd1cee317f1b0df7c
        secret: ENC(vCxECXlYDJRYs9Xzhn6VBqeZdjRGeRt6PsJfAxWT0oTpEvhp8tbM6+OEWsLmyU3GSmmrT2Sj/Vv3U/iWhIFDeB7MYT7520qdTUCl4wp5q90=)

cos:
  secret-id: AKIDTntnTu66pJZaNwKUP6YlkqiLjtpWyBAu
  secret-key: ENC(YQyNRHFTti9waIIS+gEUun/e5oKmuqrGx8+u6599kXAFBWDj1OL2RG9QA9S861uiMTJ+e+1qPJNgvACX94szaiJWNw4LqKUhorGptP0pF/w=)
  bucket-name: group-purchase-1308769147
  region: ap-beijing